[Server]
Mode = "debug"
Addr = "0.0.0.0:8888"
ReadTimeout = 60
WriteTimeout = 60

[Database]
Dialect = "mysql"
User = "root"
Password = "Xq10683766.."
Host = "xueqiya.com:3306"
Name = "gin_blog"
Protocol = "tcp"
Charset = "utf8mb4"
ParseTime = "True"
Loc = "Local"
MaxIdleConns = 10
MaxOpenConns = 100
TablePrefix = "blog_"
